### PR TITLE
Removed "warning treated as error" flag from MSVC

### PR DESCRIPTION
**Pull request by ghost**
Setting the "warning treated as error" flag in public projects is problematic, because it can lead to compilation errors for users, when the compiler adds new warnings. This however, does not mean that the project has a bug, only that it emits a new warning. Nevertheless it still fails to compile.

### CODE REVIEW

**Comment by ghost** [comment]
I signed it!

**Comment by ghost** [comment]
By the way, I mainly noticed this problem because of the following:

```
1>------ Build started: Project: absl_strings, Configuration: Debug Win32 ------
1>charconv_parse.cc
1>...\abseil-cpp\absl\strings\internal\charconv_parse.cc(372): error C2220: warning treated as error - no 'object' file generated
1>...\abseil-cpp\absl\strings\internal\charconv_parse.cc(491): note: see reference to function template instantiation 'absl::strings_internal::ParsedFloat absl::strings_internal::ParseFloat<10>(const char *,const char *,absl::chars_format)' being compiled
1>...\abseil-cpp\absl\strings\internal\charconv_parse.cc(372): warning C4018: '>=': signed/unsigned mismatch
1>...\abseil-cpp\absl\strings\internal\charconv_parse.cc(375): warning C4018: '>': signed/unsigned mismatch
1>...\abseil-cpp\absl\strings\internal\charconv_parse.cc(395): warning C4018: '>=': signed/unsigned mismatch
1>...\abseil-cpp\absl\strings\internal\charconv_parse.cc(409): warning C4018: '>=': signed/unsigned mismatch
1>...\abseil-cpp\absl\strings\internal\charconv_parse.cc(412): warning C4018: '>': signed/unsigned mismatch
1>Done building project "absl_strings.vcxproj" -- FAILED.
2>------ Build started: Project: str_format_internal, Configuration: Debug Win32 ------
2>bind.cc
2>...\abseil-cpp\absl\strings\internal\str_format\bind.cc(212): error C2220: warning treated as error - no 'object' file generated
2>...\abseil-cpp\absl\strings\internal\str_format\bind.cc(212): warning C4018: '>': signed/unsigned mismatch
2>Done building project "str_format_internal.vcxproj" -- FAILED.
3>------ Build started: Project: project, Configuration: Debug Win32 ------
3>LINK : fatal error LNK1104: cannot open file '...\abseil-cpp\absl\strings\Debug\str_format_internal.lib'
3>Done building project "project.vcxproj" -- FAILED.
========== Build: 0 succeeded, 3 failed, 32 up-to-date, 0 skipped ==========
```

I'm using `absl/strings/str_format.h` with Visual Studio 15.7.4.

**Comment by ghost** [comment]
Plus, looking at the code, there is no equivalent `-Werror` flag set for clang or gcc. However, the bazel files contain a comment that bazel includes `-Werror` implicitly.

**Comment by JonathanDCohen** [comment]
Thanks for the PR!  We still are working on spinning up windows CI for our cmake builds, so this is important to catch.

You'll need to remove /WX from MSVC_FLAGS as well from https://github.com/abseil/abseil-cpp/blob/master/absl/copts.bzl

That comment in that file under LLVM_FLAGS is actually incorrect.  You should probably remove that as well

**Comment by ghost** [comment]
Thanks! I fixed the bazel file too. I wanted to do a clean rebase of the commits, but unfortunately I can only access the GitHub webpage at the moment...

**Pull request merged**
