### PR TITLE
Add pragma alternate name support for Windows ARM64

### PR DESCRIPTION
**Pull request by ThomsonTan**
The extra declaration for `_M_IA64` and `_M_AMD64` than `_M_IX86` seems for `__ptr64` type, so it also applies to `_M_ARM64`.

### CODE REVIEW

**Comment by atetubou** [comment]
It is better to send this to
https://github.com/google/cctz
instead?

**Comment by derekmauro** [comment]
Please send this patch to https://github.com/google/cctz instead.

**Comment by ThomsonTan** [comment]
Thanks, @atetubou and @derekmauro . The PR was merged to cctz project below. How could I port that to abseil-cpp?

https://github.com/google/cctz/pull/90

**Comment by derekmauro** [comment]
@ThomsonTan - You don't have to do anything else, we will do it for you soon.

**Comment by ThomsonTan** [comment]
@derekmauro it sounds great. When will you port it or update to latest cctz? Curious because Chromium needs this to unblock abseil-cpp unittest build for Windows ARM64.

**Comment by shaindelschwartz** [comment]
Sorry for the delay - the team is offsite this week, so responses are slow. I'll push the latest Abseil now with an update to the latest CCTZ.

**Pull request closed without merging**
