### PR TITLE
Add Google-style .clang-format file.

### PR DESCRIPTION
**Pull request by EricWF**
It would be nice if the repository contained a clang-format
config file so that PR submitters could use tooling to correctly
format their code match Googles/abseils style.

This also makes it easier for reviewers to specify what coding style
should be used. ie the one the tooling produces.

The clang-format file is the default Google configuration as dumped by `clang-format`.
I'm not sure abseil will want the exact same options, but it seemed like the right
starting place.

### CODE REVIEW

**Comment by bazel-io** [comment]
Can one of the admins verify this patch?

**Comment by gennadiycivil** [comment]
test this please

**Comment by EricWF** [comment]
@gennadiycivil How would I test this? Apart from committing tests directly to Clang that test the utility directly?

**Comment by djasper** [comment]
If you want the exact same style as Google style, the file only should contain:

BasedOnStyle: Google

If the style deviates in someway, only overwrite the style flags that actually deviate.

**Comment by tituswinters** [comment]
There shouldn't be any need to deviate - AFAIK most/all of this has probably been formatted by clang-format internally under those settings.

**Comment by gennadiycivil** [comment]
@EricWF sorry for misunderstanding, this was an internal trigger for CI build... not directed to you

**Comment by EricWF** [comment]
@djasper Ack. Better now?

**Comment by EricWF** [comment]
@gennadiycivil Ha! That's a funny misunderstanding! That makes a lot more sense now, thank you.

**Comment by sunglim** [comment]
I think we can close this issue now

**Comment by gennadiycivil** [comment]
Bazel-CI: test this please

**Pull request merged**
