### PR TITLE
moved thread_safety_analysis::ts_unchecked_read to absl namespace

### PR DESCRIPTION
**Pull request by serejkus**
This solves issue #127

### CODE REVIEW

**Comment by serejkus** [comment]
I've signed CLA after receiving this message, so check should be restarted and label "cla: no" should be removed, I guess.

**Review by derekmauro — COMMENTED** [review]
This isn't so simple.

From https://abseil.io/about/compatibility
> We will not break API compatibility. If we must, we will ship a tool to automate the upgrade to a preferred API. We will never break that API in a single change - we believe in non-atomic refactoring. We will introduce the new API and the tool, wait some time, and then remove the old.

This change would technically be an API break since `thread_safety_analysis::ts_unchecked_read()` is currently a public API according to our rules. It wasn't intended to be, but that was our mistake. I just verified there is at least one use in Google's codebase calling `thread_safety_analysis::ts_unchecked_read` directly (I will send a fix for that).

In addition, we also made the error of releasing `TS_UNCHECKED_READ` instead of `ABSL_TS_UNCHECKED_READ`. For example, [Chromium also has a `TS_UNCHECKED_READ` macro](https://chromium.googlesource.com/chromium/src/base/+/b7b147ba1083870cea43fe241c7c24e21abb9fe0/thread_annotations.h), and [macro redefinition](https://gcc.gnu.org/onlinedocs/cpp/Undefining-and-Redefining-Macros.html) is a potential problem in any project that may be using both definitions.

Fixing this is going to require more work.

**Comment by serejkus** [comment]
So, what do we do here? Rename `TS_UNCHECKED_READ` to `ABSL_TS_UNCHECKED_READ`?
It is possible to make non-breaking change with something like this:
```c++
#define ABSL_TS_UNCHECKED_READ(x) absl::thread_safety_analysis::ts_unchecked_read(x)
// Deprecated. Use ABSL_TS_UNCHECKED_READ instead
#define TS_UNCHECKED_READ(x) ABSL_TS_UNCHECKED_READ(x)

namespace absl {
namespace thread_safety_analysis {
// ts_unchecked_read_here
}
}

namespace thread_safety_analysis {
  template<typename T>
  ABSL_DEPRECATED("use absl::thread_safety_analysis::ts_unchecked_read") inline const T& ts_unchecked_read(const T& v) NO_THREAD_SAFETY_ANALYSIS {
    return absl::thread_safety_analysis::ts_unchecked(v);
  }
  // ...
}
```

**Comment by derekmauro** [comment]
You can't change the definition of `TS_UNCHECKED_READ` because of the macro redefinition issue. This is something the team is going to have to handle when we have time. We will need to release a tool to update code that depends on this API.

**Pull request closed without merging**
