### PR TITLE
add xcprivacy to all subspecs

### PR DESCRIPTION
**Pull request by HannahShiSFB**
Backport #1643 to lts_2024_01_16 branch

### CODE REVIEW

**Review by derekmauro — COMMENTED** [review]
1) What testing has been done to ensure this meets the needs of users?
2) Does this need to be backported to any other branches?

**Comment by HannahShiSFB** [comment]
Tests is done in #1643, all subspecs now have xcprivacy.
They are upgrading to latest version, so 2024_01_16 should be enough 
@derekmauro

**Review by ncooke3 — APPROVED** [review]

**Comment by HannahShiSFB** [comment]
@derekmauro 
Hi Derek, could you take a look at this one? 
Hopefully, we can backport #1647 and #1639 together into 2024_01_16, and publish to cocoapods as 1.20240116.2 soon.

Thanks

@paulb777 @sampajano

**Comment by derekmauro** [comment]
I haven't had time for this, sorry.

**Comment by derekmauro** [comment]
I've cherry-picked this and a few other patches into https://github.com/abseil/abseil-cpp/releases/tag/20240116.2.

**Comment by paulb777** [comment]
Thanks. What is the process to publish the CocoaPod? I still don't see it at https://cocoapods.org/pods/abseil

**Comment by derekmauro** [comment]
> Thanks. What is the process to publish the CocoaPod? I still don't see it at https://cocoapods.org/pods/abseil

We have nothing to do that. @veblush is the maintainer of the CocoaPod.

**Comment by veblush** [comment]
[1.20240116.2](https://github.com/CocoaPods/Specs/blob/master/Specs/3/8/6/abseil/1.20240116.2/abseil.podspec.json) got released.

**Pull request closed without merging**
