### PR TITLE
[bazel] Add fixes for --incompatible_load_cc_rules_from_bzl

### PR DESCRIPTION
**Pull request by Yannic**
Starting with Bazel 1.0 (September 2019), C++ rules will need to be
loaded from the @rules_cc repository. This change adds the required
loads for that. For full compatibility, we will need versions of
googletest and google-benchmark that also includes these loads.

### CODE REVIEW

**Comment by Yannic** [comment]
@suertreus Thanks for looking at this! I see some tests are failing but I can't access the logs to see what's happening here. Is there anything that I need do to get the tests to pass?

**Comment by derekmauro** [comment]
@Yannic - Nothing you need to do. The version of Bazel on our Windows and MacOS test instances is just a bit old. We will need to upgrade, but then we can accept this. Thanks.

**Comment by Yannic** [comment]
@derekmauro I saw there were changes to the CI script on master, so I merged them into this PR. Can we re-test this?

**Comment by derekmauro** [comment]
Yes, the changes were for this PR. The tests now pass. LGTM.

**Review by derekmauro — APPROVED** [review]

**Pull request merged**
