### PR TITLE
Silence GCC warning about non-virtual-dtor of base class

### PR DESCRIPTION
**Pull request by KSSysLab**
Co-authored-by: Zhiwei Chen <condy0919@gmail.com>

### CODE REVIEW

**Comment by KSSysLab** [comment]
@googlebot I signed it!

**Comment by derekmauro** [comment]
This change causes a different problem though:
```(14:48:21) ERROR: /abseil-cpp/absl/flags/BUILD.bazel:350:8: Couldn't build file absl/flags/_objs/flag_test/flag_test.pic.o: C++ compilation of rule '//absl/flags:flag_test' failed (Exit 1) gcc failed: error executing command /usr/local/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++11' -MD -MF ... (remaining 66 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
absl/flags/flag_test.cc:142:69: error: the type 'absl::Flag<bool> {aka const absl::flags_internal::Flag<bool>}' of constexpr variable '{anonymous}::f1bool' is not literal
   constexpr absl::Flag<T> f1##T{"f1", "file", help_arg, f1default##T};     \
                                                                     ^
absl/flags/flag_test.cc:162:1: note: in expansion of macro 'DEFINE_CONSTRUCTED_FLAG'
 DEFINE_CONSTRUCTED_FLAG(bool, true, kOneWord);
 ^
In file included from ./absl/flags/flag.h:39:0,
                 from absl/flags/flag_test.cc:16:
./absl/flags/internal/flag.h:584:7: note: 'absl::flags_internal::Flag<bool>' is not literal because:
 class Flag {
       ^
./absl/flags/internal/flag.h:584:7: note:   'absl::flags_internal::Flag<bool>' has a non-trivial destructor
absl/flags/flag_test.cc:142:69: error: the type 'absl::Flag<short int> {aka const absl::flags_internal::Flag<short int>}' of constexpr variable '{anonymous}::f1int16_t' is not literal
   constexpr absl::Flag<T> f1##T{"f1", "file", help_arg, f1default##T};     \
                                                                     ^
absl/flags/flag_test.cc:163:1: note: in expansion of macro 'DEFINE_CONSTRUCTED_FLAG'
 DEFINE_CONSTRUCTED_FLAG(int16_t, 1, kOneWord);
 ^
```

I think we are doing something weird with the lifetime of flag objects. @rogeeff - can you take a look at this one?

**Comment by KSSysLab** [comment]
@googlebot I signed it!

**Comment by KSSysLab** [comment]
@googlebot I signed it!

**Review by ghost — APPROVED** [review]

**Comment by rogeeff** [comment]
The destructor is protected. It is intentionally non-virtual to keep the base class "literal". The derived class is defined final. This should be enough to silence the warning. The compiler might be wrong in this case. I believe this warning is not reported in recent compiler versions.

**Pull request closed without merging**
