### PR TITLE
`const_cast`-away volatile during copy

### PR DESCRIPTION
**Pull request by jrandolf**
In Clang 16, `HandleEdgeCase` results in an error due to a `volatile` qualifier:

```
 cannot initialize a parameter of type 'void *' with an lvalue of type 'volatile char *'
```
 
This PR removes the `volatile` qualifier during copy in `HandleEdgeCase`.

### CODE REVIEW

**Comment by derekmauro** [comment]
Tests are failing, probably because of the issue described on line 337.

@vslashg

**Comment by jrandolf** [comment]
The issue is not repaired in GCC (not unexpected). I've limited the fix to clang for now.

**Comment by derekmauro** [comment]
> The issue is not repaired in GCC (not unexpected). I've limited the fix to clang for now.

I played with the godbolt link in the bug report and this issue does not appear to be fixed in Clang 6, which is still supported according to https://github.com/google/oss-policies-info/blob/main/foundational-cxx-support-matrix.md. Can this be conditioned more precisely?

**Comment by jrandolf** [comment]
> > The issue is not repaired in GCC (not unexpected). I've limited the fix to clang for now.
> 
> I played with the godbolt link in the bug report and this issue does not appear to be fixed in Clang 6, which is still supported according to https://github.com/google/oss-policies-info/blob/main/foundational-cxx-support-matrix.md. Can this be conditioned more precisely?

Done.

**Pull request merged**
