### PR TITLE
Fix missing include

### PR DESCRIPTION
**Pull request by MBkkt**
https://github.com/abseil/abseil-cpp/commit/74d8b4d9bd5f8cf7b949b01e106c33cd0f0eba0a

`absl::c_for_each`

### CODE REVIEW

**Review by derekmauro — CHANGES_REQUESTED** [review]
Thank you for the pull request. This requires an update to the dependencies in the BUILD and CMakeLists.txt files. Can you update them?

**Comment by MBkkt** [comment]
Ok. But a little later

**Comment by MBkkt** [comment]
@derekmauro Sorry, still wasn't time, do I need to change cmake/basel, it was merged for some reason?

**Comment by derekmauro** [comment]
If you take a look at https://github.com/abseil/abseil-cpp/commit/209a595495193842acc3aa78100be8e59de314dd, I made the changes for you.

**Comment by MBkkt** [comment]
See, thanks!

**Pull request merged**
